version: "3"
services:
  back:
    working_dir: /app
    image: webdevops/php-apache-dev:8.2
    container_name: back
    depends_on:
      - db
    ports:
        - "8080:80"
    volumes:
        - .:/app
    env_file:
      - .env

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: desafio
